/**
 * Ruddur API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1alpha1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V1alpha1VirtualMachine } from './v1alpha1VirtualMachine';


export interface V1alpha1ListVirtualMachinesResponse { 
    vms?: Array<V1alpha1VirtualMachine>;
}

