/**
 * ruddur.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V1alpha1Cluster } from './v1alpha1Cluster';


export interface V1alpha1ListClustersResponse { 
    clusters?: Array<V1alpha1Cluster>;
}

