/**
 * ruddur.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { V1alpha1MachineTypeAndAmount } from './v1alpha1MachineTypeAndAmount';


export interface V1alpha1AvailableMachinesResponse { 
    machines?: Array<V1alpha1MachineTypeAndAmount>;
}

